name: time_series_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.3.0
  - numpy>=1.21.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - tqdm>=4.62.0
  - holidays>=0.14.0
  - plotly>=5.3.0
  - scikit-learn>=1.0.0
  - statsmodels>=0.12.0
  - scipy>=1.7.0
  - ipython>=7.0.0
  - graphviz 
  - pip
  - pip:
      - plotly
